### ISSUE TITLE
A way to create and execute prepared statements

### ISSUE THREAD

**Issue by michaelklishin** [clojurewerkz/cassaforte#90]
We are not willing to cache prepared statements any more but re-binding a var eliminates all the efficiency of prepared statements.

So instead we can come up with a couple of functions that:

 * Return a prepared statement
 * Execute it

**Comment by arr-ee** [comment]
Re: preparing statements and keeping them around:

Won’t something like this work? (not an existing API, might contain discrepancies of all sorts)

```clojure
(def insert-user (cql/prepare (cql/insert session :users [:uid :name :email [:admin false]])))
```

where `cql/prepare` returns a memoized function that expects a session as an argument and returns a prepared statement (an instance of [DefaultPreparedStatement](http://www.datastax.com/drivers/java/2.1/com/datastax/driver/core/DefaultPreparedStatement.html)). That way we’d get a query-level session-dependent cache that we can push into a separate namespace, shove into another datastructure, and generally pass around explicitly.

Having that prepared statement at hand, we have to a) call `.bind` at it and b) pass the result into `client/execute`. Assuming that query params are passed as a vector and are in correct order, we can implement something like `(cql/bind insert-user ["uuid-str" "Max" "email@test.com"])`, passing its result to `client/execute`.

Additionally this way we’d have a transparent way to build BATCH statements (re: #86) since driver >= 2.0 has a neat `BatchStatement` object we can `.add` both raw and prepared (& binded) queries to, having an api akin to

```clojure
(->> [["uuid1" "Max" "email1"]
      ["uuid2" "Alex" "email2"]
      ["uuid3" "Michael" "email3"]]
     (map (partial cql/bind insert-user))
     cql/batch
     (client/execute session))
```

wdyt?

**Comment by michaelklishin** [comment]
This looks close to what I had in mind.

**Comment by changgengli** [comment]
+1 vote

**Comment by ifesdjeen** [comment]
@arr-ee @michaelklishin I've started working on that one in branch. JFYI

**Comment by michaelklishin** [comment]
:+1:

**Comment by ifesdjeen** [comment]
Currently working version: 

```clojure
(let [prepared (client/prepare (insert s :users
                                                 {:name ?
                                                  :city ?
                                                  :age  ?}))
                r        {:name "Alex" :city "Munich" :age (int 19)}]
            (println
             (client/execute
              (client/bind prepared (to-array ["Alex" "Munich" (int 19)]))
              s))
            (is (= r (first (select s :users))))
            )
```

cc @arr-ee @michaelklishin  

Feedback welcome!

**Comment by michaelklishin** [comment]
Looks good but I'm not sure what exactly does the `to-array` thing do. Can we rub some internal protocol-based conversion for all collections types on it?

**Comment by ifesdjeen** [comment]
@michaelklishin ah, that is to be removed, testing/iteration artefact

**Comment by michaelklishin** [comment]
![](http://www.reactiongifs.com/r/bnc.gif)

**Comment by arr-ee** [comment]
Looks great!

I’m a bit concerned about those question marks – is that some macro magick or smth?

**Comment by mpenet** [comment]
it's a hayt var, it's fine if you dont :refer :all or use, you can just use :? instead as well.

**Comment by mpenet** [comment]
actually no :? isn't supported, I was sure it was, I ll update this now.

**Comment by arr-ee** [comment]
right, I forgot that clojure allows this. thx for the clarification

**Comment by mpenet** [comment]
well in fact I don't think I'll allow :?, keywords already have a different meaning when used in CQL Values, I'd rather not create exceptions and complicate things further.

**Comment by mpenet** [comment]
you can use '? tho, symbols skip all processing and have their string representation used as output.

internally ? is defined as a Raw type https://github.com/mpenet/hayt/blob/master/src/clj/qbits/hayt/utils.clj#L63-L68

**Comment by ifesdjeen** [comment]
@arr-ee I think @mpenet explained it better than I ever could :)

**Comment by ifesdjeen** [comment]
@arr-ee @michaelklishin ok, prepared queries are now completely fixed and working.

Although because async queries don't work anymore, we have to find some good way to execute them. How about we use async macro around the query to make it async instead (which doesn't contradict to the fact we could still have `async-*` helpers). Thoughts?

**Comment by michaelklishin** [comment]
@ifesdjeen sounds good.

**Comment by ifesdjeen** [comment]
ok async queries are much improved now. will merge to Master shortly
